server:
  port: 8082

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: postgres
    password: 13102002
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: booking-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  redis:
    host: localhost
    port: 6379

# JWT Config
jwt:
  secret: mysecretkey
  expiration: 86400000   # 1 day in ms

# Logging
logging:
  level:
    org.springframework: INFO
    com.ticketing: DEBUG